spring.application.name=Urbans-Homes

#1. info general bd
spring.datasource.url=jdbc:h2:mem:urbansHome_db
spring.datasource.username=sa
spring.datasource.password=

#2. activo h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#3. activo jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
