spring.application.name=Urbans-Homes
server.port=8080

# 1. Info general BD (H2 en memoria)
spring.datasource.url=jdbc:h2:mem:urbansHome_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# 3. Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
